//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace NoSqlTorgiGovRu {
    using LiteDB;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://torgi.gov.ru/opendata", IsNullable=false)]
    public partial class fullNotification {
        
        private fullNotificationNotification notificationField;
        
        private fullNotificationProtocol[] protocolField;
        
        /// <remarks/>
        public fullNotificationNotification notification {
            get {
                return this.notificationField;
            }
            set {
                this.notificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("protocol")]
        public fullNotificationProtocol[] protocol {
            get {
                return this.protocolField;
            }
            set {
                this.protocolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotification {
        
        private string bidNumberField;
        
        private fullNotificationNotificationBidOrganization bidOrganizationField;
        
        private fullNotificationNotificationCommon commonField;
        
        private fullNotificationNotificationDoc[] documentsField;
        
       
        private fullNotificationNotificationLot[] lotField;
        
        /// <remarks/>
        public string bidNumber {
            get {
                return this.bidNumberField;
            }
            set {
                this.bidNumberField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationBidOrganization bidOrganization {
            get {
                return this.bidOrganizationField;
            }
            set {
                this.bidOrganizationField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationCommon common {
            get {
                return this.commonField;
            }
            set {
                this.commonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("doc", IsNullable=false)]
        public fullNotificationNotificationDoc[] documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }

        /// <remarks/>
        [BsonRef(NotificationLotModel.CollectionName)]
        [System.Xml.Serialization.XmlElementAttribute("lot")]
        public fullNotificationNotificationLot[] lot {
            get {
                return this.lotField;
            }
            set {
                this.lotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationBidOrganization {
        
        private string bidOrgKindField;
        
        private long organizationIdField;
        
        private string fullNameField;
        
        private string headOrgField;
        
        private double limitBidDealField;
        
        private bool limitBidDealFieldSpecified;
        
        private string innField;
        
        private string kppField;
        
        private string okatoField;
        
        private string okpoField;
        
        private string okvedField;
        
        private string ogrnField;
        
        private string addressField;
        
        private string phoneField;
        
        private string faxField;
        
        private string locationField;
        
        private string urlField;
        
        /// <remarks/>
        public string bidOrgKind {
            get {
                return this.bidOrgKindField;
            }
            set {
                this.bidOrgKindField = value;
            }
        }
        
        /// <remarks/>
        public long organizationId {
            get {
                return this.organizationIdField;
            }
            set {
                this.organizationIdField = value;
            }
        }
        
        /// <remarks/>
        public string fullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
            }
        }
        
        /// <remarks/>
        public string headOrg {
            get {
                return this.headOrgField;
            }
            set {
                this.headOrgField = value;
            }
        }
        
        /// <remarks/>
        public double limitBidDeal {
            get {
                return this.limitBidDealField;
            }
            set {
                this.limitBidDealField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool limitBidDealSpecified {
            get {
                return this.limitBidDealFieldSpecified;
            }
            set {
                this.limitBidDealFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        public string kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        public string okato {
            get {
                return this.okatoField;
            }
            set {
                this.okatoField = value;
            }
        }
        
        /// <remarks/>
        public string okpo {
            get {
                return this.okpoField;
            }
            set {
                this.okpoField = value;
            }
        }
        
        /// <remarks/>
        public string okved {
            get {
                return this.okvedField;
            }
            set {
                this.okvedField = value;
            }
        }
        
        /// <remarks/>
        public string ogrn {
            get {
                return this.ogrnField;
            }
            set {
                this.ogrnField = value;
            }
        }
        
        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationCommon {
        
        private fullNotificationNotificationCommonBidKind bidKindField;
        
        private fullNotificationNotificationCommonBidForm bidFormField;
        
        private string bidUrlField;
        
        private string fioField;
        
        private int lotNumField;
        
        private string publishedField;
        
        private string lastChangedField;
        
        private string timeOutField;
        
        private string etpNameField;
        
        private string etpOperatorField;
        
        private string etpUrlField;
        
        private string notificationUrlField;
        
        private string startDateRequestField;
        
        private string expireDateField;
        
        private string appReceiptDetailsField;
        
        private string appRequirementField;
        
        private string appWithdrawField;
        
        private string conditionField;
        
        private string winnerDefineDateField;
        
        private string competitionConditionField;
        
        private string winnerDefinePlaceField;
        
        private string offerProcessingDateField;
        
        private string tradeProcessingDateField;
        
        private string appChangeField;
        
        private string bidAuctionDateField;
        
        private string bidAuctionPlaceField;
        
        private string summationDateField;
        
        private string processingDateField;
        
        private string processingPlaceField;
        
        private string summationPlaceField;
        
        private string bidAuctionDatePlaceField;
        
        private string winnerDefineDescrField;
        
        /// <remarks/>
        public fullNotificationNotificationCommonBidKind bidKind {
            get {
                return this.bidKindField;
            }
            set {
                this.bidKindField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationCommonBidForm bidForm {
            get {
                return this.bidFormField;
            }
            set {
                this.bidFormField = value;
            }
        }
        
        /// <remarks/>
        public string bidUrl {
            get {
                return this.bidUrlField;
            }
            set {
                this.bidUrlField = value;
            }
        }
        
        /// <remarks/>
        public string fio {
            get {
                return this.fioField;
            }
            set {
                this.fioField = value;
            }
        }
        
        /// <remarks/>
        public int lotNum {
            get {
                return this.lotNumField;
            }
            set {
                this.lotNumField = value;
            }
        }
        
        /// <remarks/>
        public string published {
            get {
                return this.publishedField;
            }
            set {
                this.publishedField = value;
            }
        }
        
        /// <remarks/>
        public string lastChanged {
            get {
                return this.lastChangedField;
            }
            set {
                this.lastChangedField = value;
            }
        }
        
        /// <remarks/>
        public string timeOut {
            get {
                return this.timeOutField;
            }
            set {
                this.timeOutField = value;
            }
        }
        
        /// <remarks/>
        public string etpName {
            get {
                return this.etpNameField;
            }
            set {
                this.etpNameField = value;
            }
        }
        
        /// <remarks/>
        public string etpOperator {
            get {
                return this.etpOperatorField;
            }
            set {
                this.etpOperatorField = value;
            }
        }
        
        /// <remarks/>
        public string etpUrl {
            get {
                return this.etpUrlField;
            }
            set {
                this.etpUrlField = value;
            }
        }
        
        /// <remarks/>
        public string notificationUrl {
            get {
                return this.notificationUrlField;
            }
            set {
                this.notificationUrlField = value;
            }
        }
        
        /// <remarks/>
        public string startDateRequest {
            get {
                return this.startDateRequestField;
            }
            set {
                this.startDateRequestField = value;
            }
        }
        
        /// <remarks/>
        public string expireDate {
            get {
                return this.expireDateField;
            }
            set {
                this.expireDateField = value;
            }
        }
        
        /// <remarks/>
        public string appReceiptDetails {
            get {
                return this.appReceiptDetailsField;
            }
            set {
                this.appReceiptDetailsField = value;
            }
        }
        
        /// <remarks/>
        public string appRequirement {
            get {
                return this.appRequirementField;
            }
            set {
                this.appRequirementField = value;
            }
        }
        
        /// <remarks/>
        public string appWithdraw {
            get {
                return this.appWithdrawField;
            }
            set {
                this.appWithdrawField = value;
            }
        }
        
        /// <remarks/>
        public string condition {
            get {
                return this.conditionField;
            }
            set {
                this.conditionField = value;
            }
        }
        
        /// <remarks/>
        public string winnerDefineDate {
            get {
                return this.winnerDefineDateField;
            }
            set {
                this.winnerDefineDateField = value;
            }
        }
        
        /// <remarks/>
        public string competitionCondition {
            get {
                return this.competitionConditionField;
            }
            set {
                this.competitionConditionField = value;
            }
        }
        
        /// <remarks/>
        public string winnerDefinePlace {
            get {
                return this.winnerDefinePlaceField;
            }
            set {
                this.winnerDefinePlaceField = value;
            }
        }
        
        /// <remarks/>
        public string offerProcessingDate {
            get {
                return this.offerProcessingDateField;
            }
            set {
                this.offerProcessingDateField = value;
            }
        }
        
        /// <remarks/>
        public string tradeProcessingDate {
            get {
                return this.tradeProcessingDateField;
            }
            set {
                this.tradeProcessingDateField = value;
            }
        }
        
        /// <remarks/>
        public string appChange {
            get {
                return this.appChangeField;
            }
            set {
                this.appChangeField = value;
            }
        }
        
        /// <remarks/>
        public string bidAuctionDate {
            get {
                return this.bidAuctionDateField;
            }
            set {
                this.bidAuctionDateField = value;
            }
        }
        
        /// <remarks/>
        public string bidAuctionPlace {
            get {
                return this.bidAuctionPlaceField;
            }
            set {
                this.bidAuctionPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string summationDate {
            get {
                return this.summationDateField;
            }
            set {
                this.summationDateField = value;
            }
        }
        
        /// <remarks/>
        public string processingDate {
            get {
                return this.processingDateField;
            }
            set {
                this.processingDateField = value;
            }
        }
        
        /// <remarks/>
        public string processingPlace {
            get {
                return this.processingPlaceField;
            }
            set {
                this.processingPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string summationPlace {
            get {
                return this.summationPlaceField;
            }
            set {
                this.summationPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string bidAuctionDatePlace {
            get {
                return this.bidAuctionDatePlaceField;
            }
            set {
                this.bidAuctionDatePlaceField = value;
            }
        }
        
        /// <remarks/>
        public string winnerDefineDescr {
            get {
                return this.winnerDefineDescrField;
            }
            set {
                this.winnerDefineDescrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationCommonBidKind {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationCommonBidForm {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationDoc {
        
        private string docTypeField;
        
        private string docDateField;
        
        private string descriptionField;
        
        private string createdField;
        
        private string docUrlField;
        
        /// <remarks/>
        public string docType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        public string docDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string docUrl {
            get {
                return this.docUrlField;
            }
            set {
                this.docUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLot {
        
        private string lotNumField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private fullNotificationNotificationLotBidStatus bidStatusField;
        
        private string cancelDateField;
        
        private string cancelReasonField;
        
        private string suspendDateField;
        
        private string suspendReasonField;
        
        private fullNotificationNotificationLotBidType bidTypeField;
        
        private fullNotificationNotificationLotPropKind propKindField;
        
        private string ownerField;
        
        private string reqDecisionField;
        
        private string cadastralNumField;
        
        private fullNotificationNotificationLotGroundType groundTypeField;
        
        private fullNotificationNotificationLotGroundUsage groundUsageField;
        
        private string missionField;
        
        private string countryField;
        
        private fullNotificationNotificationLotKladrLocation kladrLocationField;
        
        private string locationField;
        
        private fullNotificationNotificationLotUnit unitField;
        
        private double areaField;
        
        private string descriptionField;
        
        private long termYearField;
        
        private long termMonthField;
        
        private fullNotificationNotificationLotArticle articleField;
        
        private string groundInfoField;
        
        private double pricePerMonthField;
        
        private bool pricePerMonthFieldSpecified;
        
        private double pricePerYearField;
        
        private bool pricePerYearFieldSpecified;
        
        private double startPriceField;
        
        private double minPriceField;
        
        private bool minPriceFieldSpecified;
        
        private double startPriceAreaSmField;
        
        private bool startPriceAreaSmFieldSpecified;
        
        private double stepField;
        
        private bool stepFieldSpecified;
        
        private double stepNegativeField;
        
        private bool stepNegativeFieldSpecified;
        
        private double depositSizeField;
        
        private string depositDescField;
        
        private string paymentConditionsField;
        
        private string maintenanceSizeField;
        
        private string buildConditionsField;
        
        private string techConditionsField;
        
        private int isBurdenedField;
        
        private string burdenDescriptionField;
        
        private int lotPhotosExistField;
        
        private string groundViewPlaceField;
        
        private string contractTermField;
        
        private string contractDescField;
        
        private double articleValField;
        
        private bool articleValFieldSpecified;
        
        private double resultStartPriceAreaSmField;
        
        private bool resultStartPriceAreaSmFieldSpecified;
        
        private string bidResultsField;
        
        private fullNotificationNotificationLotWinner winnerField;
        
        private string currencyField;
        
        private double currencyPercentField;
        
        private bool currencyPercentFieldSpecified;
        
        private fullNotificationNotificationLotPaymentRequisites paymentRequisitesField;
        
        private fullNotificationNotificationLotDoc[] documentsField;
        
        private fullNotificationNotificationLotBidMember[] resultsField;
        
        /// <remarks/>
        public string lotNum {
            get {
                return this.lotNumField;
            }
            set {
                this.lotNumField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotBidStatus bidStatus {
            get {
                return this.bidStatusField;
            }
            set {
                this.bidStatusField = value;
            }
        }
        
        /// <remarks/>
        public string cancelDate {
            get {
                return this.cancelDateField;
            }
            set {
                this.cancelDateField = value;
            }
        }
        
        /// <remarks/>
        public string cancelReason {
            get {
                return this.cancelReasonField;
            }
            set {
                this.cancelReasonField = value;
            }
        }
        
        /// <remarks/>
        public string suspendDate {
            get {
                return this.suspendDateField;
            }
            set {
                this.suspendDateField = value;
            }
        }
        
        /// <remarks/>
        public string suspendReason {
            get {
                return this.suspendReasonField;
            }
            set {
                this.suspendReasonField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotBidType bidType {
            get {
                return this.bidTypeField;
            }
            set {
                this.bidTypeField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotPropKind propKind {
            get {
                return this.propKindField;
            }
            set {
                this.propKindField = value;
            }
        }
        
        /// <remarks/>
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        public string reqDecision {
            get {
                return this.reqDecisionField;
            }
            set {
                this.reqDecisionField = value;
            }
        }
        
        /// <remarks/>
        public string cadastralNum {
            get {
                return this.cadastralNumField;
            }
            set {
                this.cadastralNumField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotGroundType groundType {
            get {
                return this.groundTypeField;
            }
            set {
                this.groundTypeField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotGroundUsage groundUsage {
            get {
                return this.groundUsageField;
            }
            set {
                this.groundUsageField = value;
            }
        }
        
        /// <remarks/>
        public string mission {
            get {
                return this.missionField;
            }
            set {
                this.missionField = value;
            }
        }
        
        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotKladrLocation kladrLocation {
            get {
                return this.kladrLocationField;
            }
            set {
                this.kladrLocationField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotUnit unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        public double area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public long termYear {
            get {
                return this.termYearField;
            }
            set {
                this.termYearField = value;
            }
        }
        
        /// <remarks/>
        public long termMonth {
            get {
                return this.termMonthField;
            }
            set {
                this.termMonthField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotArticle article {
            get {
                return this.articleField;
            }
            set {
                this.articleField = value;
            }
        }
        
        /// <remarks/>
        public string groundInfo {
            get {
                return this.groundInfoField;
            }
            set {
                this.groundInfoField = value;
            }
        }
        
        /// <remarks/>
        public double pricePerMonth {
            get {
                return this.pricePerMonthField;
            }
            set {
                this.pricePerMonthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pricePerMonthSpecified {
            get {
                return this.pricePerMonthFieldSpecified;
            }
            set {
                this.pricePerMonthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double pricePerYear {
            get {
                return this.pricePerYearField;
            }
            set {
                this.pricePerYearField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool pricePerYearSpecified {
            get {
                return this.pricePerYearFieldSpecified;
            }
            set {
                this.pricePerYearFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double startPrice {
            get {
                return this.startPriceField;
            }
            set {
                this.startPriceField = value;
            }
        }
        
        /// <remarks/>
        public double minPrice {
            get {
                return this.minPriceField;
            }
            set {
                this.minPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minPriceSpecified {
            get {
                return this.minPriceFieldSpecified;
            }
            set {
                this.minPriceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double startPriceAreaSm {
            get {
                return this.startPriceAreaSmField;
            }
            set {
                this.startPriceAreaSmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startPriceAreaSmSpecified {
            get {
                return this.startPriceAreaSmFieldSpecified;
            }
            set {
                this.startPriceAreaSmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double step {
            get {
                return this.stepField;
            }
            set {
                this.stepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stepSpecified {
            get {
                return this.stepFieldSpecified;
            }
            set {
                this.stepFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double stepNegative {
            get {
                return this.stepNegativeField;
            }
            set {
                this.stepNegativeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stepNegativeSpecified {
            get {
                return this.stepNegativeFieldSpecified;
            }
            set {
                this.stepNegativeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double depositSize {
            get {
                return this.depositSizeField;
            }
            set {
                this.depositSizeField = value;
            }
        }
        
        /// <remarks/>
        public string depositDesc {
            get {
                return this.depositDescField;
            }
            set {
                this.depositDescField = value;
            }
        }
        
        /// <remarks/>
        public string paymentConditions {
            get {
                return this.paymentConditionsField;
            }
            set {
                this.paymentConditionsField = value;
            }
        }
        
        /// <remarks/>
        public string maintenanceSize {
            get {
                return this.maintenanceSizeField;
            }
            set {
                this.maintenanceSizeField = value;
            }
        }
        
        /// <remarks/>
        public string buildConditions {
            get {
                return this.buildConditionsField;
            }
            set {
                this.buildConditionsField = value;
            }
        }
        
        /// <remarks/>
        public string techConditions {
            get {
                return this.techConditionsField;
            }
            set {
                this.techConditionsField = value;
            }
        }
        
        /// <remarks/>
        public int isBurdened {
            get {
                return this.isBurdenedField;
            }
            set {
                this.isBurdenedField = value;
            }
        }
        
        /// <remarks/>
        public string burdenDescription {
            get {
                return this.burdenDescriptionField;
            }
            set {
                this.burdenDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public int lotPhotosExist {
            get {
                return this.lotPhotosExistField;
            }
            set {
                this.lotPhotosExistField = value;
            }
        }
        
        /// <remarks/>
        public string groundViewPlace {
            get {
                return this.groundViewPlaceField;
            }
            set {
                this.groundViewPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string contractTerm {
            get {
                return this.contractTermField;
            }
            set {
                this.contractTermField = value;
            }
        }
        
        /// <remarks/>
        public string contractDesc {
            get {
                return this.contractDescField;
            }
            set {
                this.contractDescField = value;
            }
        }
        
        /// <remarks/>
        public double articleVal {
            get {
                return this.articleValField;
            }
            set {
                this.articleValField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool articleValSpecified {
            get {
                return this.articleValFieldSpecified;
            }
            set {
                this.articleValFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double resultStartPriceAreaSm {
            get {
                return this.resultStartPriceAreaSmField;
            }
            set {
                this.resultStartPriceAreaSmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultStartPriceAreaSmSpecified {
            get {
                return this.resultStartPriceAreaSmFieldSpecified;
            }
            set {
                this.resultStartPriceAreaSmFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string bidResults {
            get {
                return this.bidResultsField;
            }
            set {
                this.bidResultsField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotWinner winner {
            get {
                return this.winnerField;
            }
            set {
                this.winnerField = value;
            }
        }
        
        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        public double currencyPercent {
            get {
                return this.currencyPercentField;
            }
            set {
                this.currencyPercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool currencyPercentSpecified {
            get {
                return this.currencyPercentFieldSpecified;
            }
            set {
                this.currencyPercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationNotificationLotPaymentRequisites paymentRequisites {
            get {
                return this.paymentRequisitesField;
            }
            set {
                this.paymentRequisitesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("doc", IsNullable=false)]
        public fullNotificationNotificationLotDoc[] documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("bidMember", IsNullable=false)]
        public fullNotificationNotificationLotBidMember[] results {
            get {
                return this.resultsField;
            }
            set {
                this.resultsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotBidStatus {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotBidType {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotPropKind {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotGroundType {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotGroundUsage {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotKladrLocation {
        
        private string idField;
        
        private string nameField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotUnit {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotArticle {
        
        private long idField;
        
        private string nameField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotWinner {
        
        private string nameField;
        
        private string innField;
        
        private string kppField;
        
        private string ogrnipField;
        
        private string ogrnField;
        
        private string locationField;
        
        private string phoneField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        public string kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        public string ogrnip {
            get {
                return this.ogrnipField;
            }
            set {
                this.ogrnipField = value;
            }
        }
        
        /// <remarks/>
        public string ogrn {
            get {
                return this.ogrnField;
            }
            set {
                this.ogrnField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotPaymentRequisites {
        
        private string bikField;
        
        private string bankNameField;
        
        private string ksField;
        
        private string rsField;
        
        private string psField;
        
        /// <remarks/>
        public string bik {
            get {
                return this.bikField;
            }
            set {
                this.bikField = value;
            }
        }
        
        /// <remarks/>
        public string bankName {
            get {
                return this.bankNameField;
            }
            set {
                this.bankNameField = value;
            }
        }
        
        /// <remarks/>
        public string ks {
            get {
                return this.ksField;
            }
            set {
                this.ksField = value;
            }
        }
        
        /// <remarks/>
        public string rs {
            get {
                return this.rsField;
            }
            set {
                this.rsField = value;
            }
        }
        
        /// <remarks/>
        public string ps {
            get {
                return this.psField;
            }
            set {
                this.psField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotDoc {
        
        private string docTypeField;
        
        private string docDateField;
        
        private string docNumField;
        
        private string descriptionField;
        
        private string createdField;
        
        private string docUrlField;
        
        /// <remarks/>
        public string docType {
            get {
                return this.docTypeField;
            }
            set {
                this.docTypeField = value;
            }
        }
        
        /// <remarks/>
        public string docDate {
            get {
                return this.docDateField;
            }
            set {
                this.docDateField = value;
            }
        }
        
        /// <remarks/>
        public string docNum {
            get {
                return this.docNumField;
            }
            set {
                this.docNumField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string docUrl {
            get {
                return this.docUrlField;
            }
            set {
                this.docUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationNotificationLotBidMember {
        
        private string regNumField;
        
        private string nameField;
        
        private string innField;
        
        private string kppField;
        
        private string ogrnField;
        
        private string locationField;
        
        private string phoneField;
        
        private int isSelectedField;
        
        private bool isSelectedFieldSpecified;
        
        private string refuseReasonField;
        
        private int tenderPositionField;
        
        private bool tenderPositionFieldSpecified;
        
        private double offerField;
        
        private bool offerFieldSpecified;
        
        /// <remarks/>
        public string regNum {
            get {
                return this.regNumField;
            }
            set {
                this.regNumField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        public string kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        public string ogrn {
            get {
                return this.ogrnField;
            }
            set {
                this.ogrnField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public int isSelected {
            get {
                return this.isSelectedField;
            }
            set {
                this.isSelectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSelectedSpecified {
            get {
                return this.isSelectedFieldSpecified;
            }
            set {
                this.isSelectedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string refuseReason {
            get {
                return this.refuseReasonField;
            }
            set {
                this.refuseReasonField = value;
            }
        }
        
        /// <remarks/>
        public int tenderPosition {
            get {
                return this.tenderPositionField;
            }
            set {
                this.tenderPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tenderPositionSpecified {
            get {
                return this.tenderPositionFieldSpecified;
            }
            set {
                this.tenderPositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offerSpecified {
            get {
                return this.offerFieldSpecified;
            }
            set {
                this.offerFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationProtocol {
        
        private string protocolTypeField;
        
        private string protocolNumField;
        
        private string prepareDateField;
        
        private string preparePlaceField;
        
        private string descriptionField;
        
        private string fileNameField;
        
        private string protocolTownField;
        
        private string protocolDateField;
        
        private string protocolPlaceField;
        
        private fullNotificationProtocolCommittee committeeField;
        
        private fullNotificationProtocolLot[] lotField;
        
        /// <remarks/>
        public string protocolType {
            get {
                return this.protocolTypeField;
            }
            set {
                this.protocolTypeField = value;
            }
        }
        
        /// <remarks/>
        public string protocolNum {
            get {
                return this.protocolNumField;
            }
            set {
                this.protocolNumField = value;
            }
        }
        
        /// <remarks/>
        public string prepareDate {
            get {
                return this.prepareDateField;
            }
            set {
                this.prepareDateField = value;
            }
        }
        
        /// <remarks/>
        public string preparePlace {
            get {
                return this.preparePlaceField;
            }
            set {
                this.preparePlaceField = value;
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public string protocolTown {
            get {
                return this.protocolTownField;
            }
            set {
                this.protocolTownField = value;
            }
        }
        
        /// <remarks/>
        public string protocolDate {
            get {
                return this.protocolDateField;
            }
            set {
                this.protocolDateField = value;
            }
        }
        
        /// <remarks/>
        public string protocolPlace {
            get {
                return this.protocolPlaceField;
            }
            set {
                this.protocolPlaceField = value;
            }
        }
        
        /// <remarks/>
        public fullNotificationProtocolCommittee committee {
            get {
                return this.committeeField;
            }
            set {
                this.committeeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lot")]
        public fullNotificationProtocolLot[] lot {
            get {
                return this.lotField;
            }
            set {
                this.lotField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationProtocolCommittee {
        
        private fullNotificationProtocolCommitteeMember[] memberField;
        
        private double committePercentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("member")]
        public fullNotificationProtocolCommitteeMember[] member {
            get {
                return this.memberField;
            }
            set {
                this.memberField = value;
            }
        }
        
        /// <remarks/>
        public double committePercent {
            get {
                return this.committePercentField;
            }
            set {
                this.committePercentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationProtocolCommitteeMember {
        
        private string nameField;
        
        private string roleField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationProtocolLot {
        
        private string lotNumField;
        
        private string cancelReasonField;
        
        private fullNotificationProtocolLotBidMember[] bidMemberField;
        
        private string criterionField;
        
        private fullNotificationProtocolLotDoc[] documentsField;
        
        private string decisionField;
        
        /// <remarks/>
        public string lotNum {
            get {
                return this.lotNumField;
            }
            set {
                this.lotNumField = value;
            }
        }
        
        /// <remarks/>
        public string cancelReason {
            get {
                return this.cancelReasonField;
            }
            set {
                this.cancelReasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bidMember")]
        public fullNotificationProtocolLotBidMember[] bidMember {
            get {
                return this.bidMemberField;
            }
            set {
                this.bidMemberField = value;
            }
        }
        
        /// <remarks/>
        public string criterion {
            get {
                return this.criterionField;
            }
            set {
                this.criterionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("doc", IsNullable=false)]
        public fullNotificationProtocolLotDoc[] documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
        
        /// <remarks/>
        public string decision {
            get {
                return this.decisionField;
            }
            set {
                this.decisionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationProtocolLotBidMember {
        
        private string regNumField;
        
        private string nameField;
        
        private string innField;
        
        private string kppField;
        
        private string ogrnField;
        
        private string locationField;
        
        private string phoneField;
        
        private int isSelectedField;
        
        private bool isSelectedFieldSpecified;
        
        private string refuseReasonField;
        
        private int tenderPositionField;
        
        private bool tenderPositionFieldSpecified;
        
        private double finalScoreField;
        
        private bool finalScoreFieldSpecified;
        
        private int attendedField;
        
        private bool attendedFieldSpecified;
        
        private double offerField;
        
        private bool offerFieldSpecified;
        
        private string documentsField;
        
        private string rejectReasonField;
        
        private int isRemovedField;
        
        private bool isRemovedFieldSpecified;
        
        private string docExistField;
        
        private int docConformedField;
        
        private bool docConformedFieldSpecified;
        
        private string considerResultField;
        
        /// <remarks/>
        public string regNum {
            get {
                return this.regNumField;
            }
            set {
                this.regNumField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string inn {
            get {
                return this.innField;
            }
            set {
                this.innField = value;
            }
        }
        
        /// <remarks/>
        public string kpp {
            get {
                return this.kppField;
            }
            set {
                this.kppField = value;
            }
        }
        
        /// <remarks/>
        public string ogrn {
            get {
                return this.ogrnField;
            }
            set {
                this.ogrnField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public int isSelected {
            get {
                return this.isSelectedField;
            }
            set {
                this.isSelectedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isSelectedSpecified {
            get {
                return this.isSelectedFieldSpecified;
            }
            set {
                this.isSelectedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string refuseReason {
            get {
                return this.refuseReasonField;
            }
            set {
                this.refuseReasonField = value;
            }
        }
        
        /// <remarks/>
        public int tenderPosition {
            get {
                return this.tenderPositionField;
            }
            set {
                this.tenderPositionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tenderPositionSpecified {
            get {
                return this.tenderPositionFieldSpecified;
            }
            set {
                this.tenderPositionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double finalScore {
            get {
                return this.finalScoreField;
            }
            set {
                this.finalScoreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool finalScoreSpecified {
            get {
                return this.finalScoreFieldSpecified;
            }
            set {
                this.finalScoreFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int attended {
            get {
                return this.attendedField;
            }
            set {
                this.attendedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attendedSpecified {
            get {
                return this.attendedFieldSpecified;
            }
            set {
                this.attendedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool offerSpecified {
            get {
                return this.offerFieldSpecified;
            }
            set {
                this.offerFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string documents {
            get {
                return this.documentsField;
            }
            set {
                this.documentsField = value;
            }
        }
        
        /// <remarks/>
        public string rejectReason {
            get {
                return this.rejectReasonField;
            }
            set {
                this.rejectReasonField = value;
            }
        }
        
        /// <remarks/>
        public int isRemoved {
            get {
                return this.isRemovedField;
            }
            set {
                this.isRemovedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isRemovedSpecified {
            get {
                return this.isRemovedFieldSpecified;
            }
            set {
                this.isRemovedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string docExist {
            get {
                return this.docExistField;
            }
            set {
                this.docExistField = value;
            }
        }
        
        /// <remarks/>
        public int docConformed {
            get {
                return this.docConformedField;
            }
            set {
                this.docConformedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool docConformedSpecified {
            get {
                return this.docConformedFieldSpecified;
            }
            set {
                this.docConformedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string considerResult {
            get {
                return this.considerResultField;
            }
            set {
                this.considerResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://torgi.gov.ru/opendata")]
    public partial class fullNotificationProtocolLotDoc {
        
        private string descriptionField;
        
        private string createdField;
        
        private string docUrlField;
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        public string docUrl {
            get {
                return this.docUrlField;
            }
            set {
                this.docUrlField = value;
            }
        }
    }
}
