//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// Этот исходный код был создан с помощью xsd, версия=4.8.3928.0.
// 
namespace NoSqlTorgiGovRu
{




    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://torgi.gov.ru/opendata")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://torgi.gov.ru/opendata", IsNullable = false)]
    public partial class openData
    {

        private openDataNotification[] notificationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("notification")]
        public openDataNotification[] notification
        {
            get { return this.notificationField; }
            set { this.notificationField = value; }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://torgi.gov.ru/opendata")]
    public partial class openDataNotification
    {


        private long bidKindIdField;

        private string bidKindNameField;

        private string bidNumberField;

        private string organizationNameField;

        private int isArchivedField;

        private System.DateTime publishDateField;

        private System.DateTime lastChangedField;

        private string odDetailedHrefField;

        /// <remarks/>
        public long bidKindId
        {
            get { return this.bidKindIdField; }
            set { this.bidKindIdField = value; }
        }

        /// <remarks/>
        public string bidKindName
        {
            get { return this.bidKindNameField; }
            set { this.bidKindNameField = value; }
        }

        /// <remarks/>
        public string bidNumber
        {
            get { return this.bidNumberField; }
            set { this.bidNumberField = value; }
        }

        /// <remarks/>
        public string organizationName
        {
            get { return this.organizationNameField; }
            set { this.organizationNameField = value; }
        }

        /// <remarks/>
        public int isArchived
        {
            get { return this.isArchivedField; }
            set { this.isArchivedField = value; }
        }

        /// <remarks/>
        public System.DateTime publishDate
        {
            get { return this.publishDateField; }
            set { this.publishDateField = value; }
        }

        /// <remarks/>
        public System.DateTime lastChanged
        {
            get { return this.lastChangedField; }
            set { this.lastChangedField = value; }
        }

        /// <remarks/>
        public string odDetailedHref
        {
            get { return this.odDetailedHrefField; }
            set { this.odDetailedHrefField = value; }
        }


    }
}
